spring.application.name=CRM_backend


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/Estatecrm
spring.datasource.username=root
spring.datasource.password=Shubhpiyu@82
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto = update
server.port=8080
spring.security.user.name=admin
spring.security.user.password=admin123

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vinaychandore13@gmail.com
spring.mail.password=aevp bgoc owop xodb

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true